### PR TITLE
 Link to HTTP proxy instructions in "failed to download" error.

### LINKED ISSUE #84: Improve error message for failed download due to HTTP proxy
Followup of https://github.com/scalameta/metals/issues/529

We should document how to configure HTTP proxies if the Metals download step fails 

https://github.com/scalameta/metals-vscode/blob/f8a49bae54af41a722beab860495879de7431dd2/src/extension.ts#L148-L155

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #84. Previously, the download error message only said "make sure
you have an internet connection" when the most common cause for this
problem was HTTP proxies. Now, the error message links to the Metals
website for how to configure HTTP proxies.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -139,6 +141,9 @@ function fetchAndLaunchMetals(context: ExtensionContext, javaHome: string) {
     },
     () => {
       const msg = (() => {
+        const proxy =
+          `See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions ` +
```
Comment (gabro) [inline src/extension.ts]: 👍 for linking to the website. It's worth to keep in mind that we better not break those urls going forward

File: src/extension.ts [hunk 2]
```diff
@@ -139,6 +141,9 @@ function fetchAndLaunchMetals(context: ExtensionContext, javaHome: string) {
...
+          `if you are using a corporate HTTP proxy.`;
```
Comment (gabro) [inline src/extension.ts]:
```suggestion
          `if you are using an HTTP proxy.`;
```

Not all proxies are corporate (e.g. universities)

Comment (olafurpg) [reply src/extension.ts]: Good point 👍
